- id: 3000_electrical_room_fan_overheat_on
  alias: Щитовая - перегрев, включить вентиляцию
  trigger:
  - platform: state
    entity_id: binary_sensor.temperatura_it_shchita_slishkom_vysoka
    to: 'on'
  action:
  - service: fan.turn_on
    target:
      entity_id: fan.rele_17_8
  mode: single
- id: 3000_electrical_room_fan_min_runtime
  alias: Щитовая - минимальное время работы вентилятора
  trigger:
  - platform: state
    entity_id: fan.rele_17_8
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: input_number.vremia_raboty_ventiliatsii_master_garderop_shchitovaia_min_0_ne_otkliuchat
    above: 0
  action:
  - delay:
      minutes: '{{ states(''input_number.vremia_raboty_ventiliatsii_master_garderop_shchitovaia_min_0_ne_otkliuchat'')
        | int(0) }}'
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.temperatura_it_shchita_slishkom_vysoka
        state: 'on'
      sequence: []
    default:
    - service: fan.turn_off
      target:
        entity_id: fan.rele_17_8
  mode: restart
- id: 3000_electrical_room_fan_temperature_normal
  alias: Щитовая - температура нормализовалась
  trigger:
  - platform: state
    entity_id: binary_sensor.temperatura_it_shchita_slishkom_vysoka
    to: 'off'
  condition:
  - condition: numeric_state
    entity_id: input_number.vremia_raboty_ventiliatsii_master_garderop_shchitovaia_min_0_ne_otkliuchat
    below: 1
  action:
  - service: fan.turn_off
    target:
      entity_id: fan.rele_17_8
  mode: single
- id: 3000_master_sanuzel_room_fan_min_runtime
  alias: Мастер санузел - таймер автоотключения вентилятора
  triggers:
  - trigger: state
    entity_id: fan.rele_17_6
    from: 'off'
    to: 'on'
  conditions:
  - condition: numeric_state
    entity_id: input_number.vremia_raboty_ventiliatsii_master_sanuzla_min_0_ne_otkliuchat
    above: 0
  actions:
  - delay:
      minutes: '{{ states(''input_number.vremia_raboty_ventiliatsii_master_sanuzla_min_0_ne_otkliuchat'')
        | int(0) }}'
  - condition: state
    entity_id: fan.rele_17_6
    state: 'on'
  - action: fan.turn_off
    target:
      entity_id: fan.rele_17_6
  mode: restart
- id: 3000_gostevoy_sanuzel_room_fan_min_runtime
  alias: Гостевой санузел - таймер автоотключения вентилятора
  triggers:
  - trigger: state
    entity_id: fan.rele_17_5
    from: 'off'
    to: 'on'
  conditions:
  - condition: numeric_state
    entity_id: input_number.vremia_raboty_ventiliatsii_gostevoi_sanuzel_min_0_ne_otkliuchat
    above: 0
  actions:
  - delay:
      minutes: '{{ states(''input_number.vremia_raboty_ventiliatsii_gostevoi_sanuzel_min_0_ne_otkliuchat'')
        | int(0) }}'
  - condition: state
    entity_id: fan.rele_17_5
    state: 'on'
  - action: fan.turn_off
    target:
      entity_id: fan.rele_17_5
  mode: restart
