version: 5
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: keeNoo6iodooNia1ThohYoh1aba2oiB6ua9Gu9eechu1Heishei8moodae1icho7
serial:
  port: tcp://192.168.0.7:6638
  adapter: ember
  baudrate: 115200
  rtscts: false
advanced:
  log_level: debug
  output: json
  channel: 11
  network_key:
    - 245
    - 61
    - 198
    - 105
    - 212
    - 215
    - 146
    - 240
    - 169
    - 190
    - 94
    - 114
    - 216
    - 40
    - 16
    - 143
  pan_id: 56219
  ext_pan_id:
    - 240
    - 105
    - 80
    - 85
    - 152
    - 50
    - 48
    - 15
  enable_external_js: false
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0xa4c13895ac983d77':
    friendly_name: Термометр  мастер санузел (1)
  '0xa4c1382b45495856':
    friendly_name: Термометр спальня (2)
  '0xa4c1384231250eb0':
    friendly_name: Термометр гостиная (3)
  '0xa4c13884b4e451e9':
    friendly_name: Термометр столовая (4)
  '0xa4c138ab83c9038f':
    friendly_name: Термометр кухня (5)
  '0xa4c1387452702877':
    friendly_name: Термометр кабинет (6)
  '0xa4c1380693d4b915':
    friendly_name: Датчик двери спальня (1)
  '0xa4c138750f623944':
    friendly_name: Датчик двери столовая (2)
  '0xa4c1388790286059':
    friendly_name: Датчик двери кабинет (3)
  '0xa4c138a3d23d33fe':
    friendly_name: Пульт штор мастер санузел (1)
  '0xa4c138e63b40600a':
    friendly_name: Пульт штор вход спальня (2)
  '0xa4c1381d03c7c244':
    friendly_name: Пульт штор спальня кровать слева (3)
  '0xa4c13807fa8ddd10':
    friendly_name: Пульт штор спальня кровать справа (4)
  '0xa4c138e016f4bb7d':
    friendly_name: Пульт штор балкон спальня (5)
  '0xa4c138b16127af83':
    friendly_name: Пульт штор гостиная (6)
  '0xa4c138f13aa390e6':
    friendly_name: Пульт штор вход столовая (7)
  '0xa4c1386504229bff':
    friendly_name: Пульт штор столовая балкон (8)
  '0xa4c138aaf9a993bb':
    friendly_name: Пульт штор кухня (9)
  '0xa4c1388fcd9881ac':
    friendly_name: Пульт штор вход кабинет (10)
  '0xa4c13884bc09205f':
    friendly_name: Пульт штор балкон кабинет (11)
  '0xa4c138e34396ed9a':
    friendly_name: Пульт штор кухня стол (9.1)
  '0xa4c13847decdbe51':
    friendly_name: Датчик вент.2 гостиная (5)
  '0xa4c138d34bfe20a6':
    friendly_name: Датчик вент.1 гостиная (4)
