# self path: /config/packages/curtains/mqtt_running.yaml

mqtt:
  binary_sensor:
    # ============================================================================
    # ГОСТИНАЯ
    # ============================================================================
    - name: "Штора (Движение): Гостиная"
      unique_id: gostinaya_shtora_running
      state_topic: "zigbee2mqtt/Гостиная штора"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Тюль (Движение): Гостиная"
      unique_id: gostinaya_tyul_running
      state_topic: "zigbee2mqtt/Гостиная тюль"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи центр (Движение): Гостиная"
      unique_id: gostinaya_zhaluzi_tsentr_running
      state_topic: "zigbee2mqtt/Гостиная жалюзи центр"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи лево (Движение): Гостиная"
      unique_id: gostinaya_zhaluzi_levo_running
      state_topic: "zigbee2mqtt/Гостиная жалюзи лево"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи право (Движение): Гостиная"
      unique_id: gostinaya_zhaluzi_pravo_running
      state_topic: "zigbee2mqtt/Гостиная  жалюзи право"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    # ============================================================================
    # КАБИНЕТ
    # ============================================================================
    - name: "Штора (Движение): Кабинет"
      unique_id: kabinet_shtora_running
      state_topic: "zigbee2mqtt/Кабинет штора"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Тюль (Движение): Кабинет"
      unique_id: kabinet_tyul_running
      state_topic: "zigbee2mqtt/Кабинет тюль"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи окно (Движение): Кабинет"
      unique_id: kabinet_zhaluzi_okno_running
      state_topic: "zigbee2mqtt/Кабинет жалюзи окно"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Сонце дверь (Движение): Кабинет"
      unique_id: kabinet_sontse_dver_running
      state_topic: "zigbee2mqtt/Кабинет сонце дверь"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    # ============================================================================
    # КУХНЯ
    # ============================================================================
    - name: "Штора (Движение): Кухня"
      unique_id: kukhnya_shtora_running
      state_topic: "zigbee2mqtt/Кухня штора"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Тюль (Движение): Кухня"
      unique_id: kukhnya_tyul_running
      state_topic: "zigbee2mqtt/Кухня тюль"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи (Движение): Кухня"
      unique_id: kukhnya_zhaluzi_running
      state_topic: "zigbee2mqtt/Кухня жалюзи"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    # ============================================================================
    # МАСТЕР САНУЗЕЛ
    # ============================================================================
    - name: "Штора (Движение): Мастер санузел"
      unique_id: master_sanzuel_shtora_running
      state_topic: "zigbee2mqtt/Мастер санузел штора"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Тюль (Движение): Мастер санузел"
      unique_id: master_sanzuel_tyul_running
      state_topic: "zigbee2mqtt/Мастер санузел тюль"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи (Движение): Мастер санузел"
      unique_id: master_sanzuel_zhaluzi_running
      state_topic: "zigbee2mqtt/Мастер санузел жалюзи"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    # ============================================================================
    # СПАЛЬНЯ
    # ============================================================================
    - name: "Балкон штора (Движение): Спальня"
      unique_id: spalnya_balkon_shtora_running
      state_topic: "zigbee2mqtt/Спальня балкон штора"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Балкон тюль (Движение): Спальня"
      unique_id: spalnya_balkon_tyul_running
      state_topic: "zigbee2mqtt/Спальня балкон тюль"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Балкон окно (Движение): Спальня"
      unique_id: spalnya_balkon_okno_running
      state_topic: "zigbee2mqtt/Спальня балкон окно"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Штора угол (Движение): Спальня"
      unique_id: spalnya_shtora_ugol_running
      state_topic: "zigbee2mqtt/Спальня  штора угол"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Тюль угол (Движение): Спальня"
      unique_id: spalnya_tyul_ugol_running
      state_topic: "zigbee2mqtt/Спальня тюль угол"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи балкон дверь (Движение): Спальня"
      unique_id: spalnya_zhaluzi_balkon_dver_running
      state_topic: "zigbee2mqtt/Спальня  жалюзи балкон дверь"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи окно левое (Движение): Спальня"
      unique_id: spalnya_zhaluzi_okno_levoe_running
      state_topic: "zigbee2mqtt/Спальня жалюзи окно левое"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи окно правое (Движение): Спальня"
      unique_id: spalnya_zhaluzi_okno_pravoe_running
      state_topic: "zigbee2mqtt/Спальня жалюзи окно правое"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    # ============================================================================
    # СТОЛОВАЯ
    # ============================================================================
    - name: "Шторы балкон (Движение): Столовая"
      unique_id: stolovaya_shtory_balkon_running
      state_topic: "zigbee2mqtt/Столовая шторы балкон"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Штора угловая (Движение): Столовая"
      unique_id: stolovaya_shtora_uglovaya_running
      state_topic: "zigbee2mqtt/Столовая штора угловая"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Тюль балкон (Движение): Столовая"
      unique_id: stolovaya_tyul_balkon_running
      state_topic: "zigbee2mqtt/Столовая тюль балкон"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Тюль угловая (Движение): Столовая"
      unique_id: stolovaya_tyul_uglovaya_running
      state_topic: "zigbee2mqtt/Столовая тюль угловая"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи балкон дверь (Движение): Столовая"
      unique_id: stolovaya_zhaluzi_balkon_dver_running
      state_topic: "zigbee2mqtt/Столовая жалюзи балкон дверь"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи балкон большой (Движение): Столовая"
      unique_id: stolovaya_zhaluzi_balkon_bolshoy_running
      state_topic: "zigbee2mqtt/Столовая жалюзи балкон большой"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи окно левое (Движение): Столовая"
      unique_id: stolovaya_zhaluzi_okno_levoe_running
      state_topic: "zigbee2mqtt/Столовая жалюзи окно левое"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off

    - name: "Жалюзи окно правое (Движение): Столовая"
      unique_id: stolovaya_zhaluzi_okno_pravoe_running
      state_topic: "zigbee2mqtt/Столовая жалюзи окно правое"
      value_template: "{{ value_json.running == true }}"
      device_class: moving
      payload_on: on
      payload_off: off