# храним промежуточные переменные / константы
# /config/packages/curtains/values.yaml

# Константы (пороги)
input_number:
  curtain_closed_threshold:
    name: "Порог закрытия (%)"
    initial: 5
    min: 0
    max: 100
    step: 1
    mode: box
    
  curtain_open_threshold:
    name: "Порог открытия (%)"
    initial: 95
    min: 0
    max: 100
    step: 1
    mode: box


# Виртуальные датчики (template binary_sensor)
template:
  - binary_sensor:
      - name: "Вентиляция открыта: Гостиная"
        unique_id: gostinaya_vent_open
        state: >
          {{ is_state('binary_sensor.0xa4c138d34bfe20a6_contact', 'on') 
          or is_state('binary_sensor.0xa4c13847decdbe51_contact', 'on') }}
        device_class: opening